// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "cms_api/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ContentRepository is an autogenerated mock type for the ContentRepository type
type ContentRepository struct {
	mock.Mock
}

type ContentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ContentRepository) EXPECT() *ContentRepository_Expecter {
	return &ContentRepository_Expecter{mock: &_m.Mock}
}

// CreateArticle provides a mock function with given fields: content
func (_m *ContentRepository) CreateArticle(content *model.Article) error {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for CreateArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Article) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContentRepository_CreateArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArticle'
type ContentRepository_CreateArticle_Call struct {
	*mock.Call
}

// CreateArticle is a helper method to define mock.On call
//   - content *model.Article
func (_e *ContentRepository_Expecter) CreateArticle(content interface{}) *ContentRepository_CreateArticle_Call {
	return &ContentRepository_CreateArticle_Call{Call: _e.mock.On("CreateArticle", content)}
}

func (_c *ContentRepository_CreateArticle_Call) Run(run func(content *model.Article)) *ContentRepository_CreateArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Article))
	})
	return _c
}

func (_c *ContentRepository_CreateArticle_Call) Return(_a0 error) *ContentRepository_CreateArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContentRepository_CreateArticle_Call) RunAndReturn(run func(*model.Article) error) *ContentRepository_CreateArticle_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArticle provides a mock function with given fields: id
func (_m *ContentRepository) DeleteArticle(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContentRepository_DeleteArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArticle'
type ContentRepository_DeleteArticle_Call struct {
	*mock.Call
}

// DeleteArticle is a helper method to define mock.On call
//   - id string
func (_e *ContentRepository_Expecter) DeleteArticle(id interface{}) *ContentRepository_DeleteArticle_Call {
	return &ContentRepository_DeleteArticle_Call{Call: _e.mock.On("DeleteArticle", id)}
}

func (_c *ContentRepository_DeleteArticle_Call) Run(run func(id string)) *ContentRepository_DeleteArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ContentRepository_DeleteArticle_Call) Return(_a0 error) *ContentRepository_DeleteArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContentRepository_DeleteArticle_Call) RunAndReturn(run func(string) error) *ContentRepository_DeleteArticle_Call {
	_c.Call.Return(run)
	return _c
}

// GetArticles provides a mock function with given fields: ctx
func (_m *ContentRepository) GetArticles(ctx context.Context) ([]model.Article, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetArticles")
	}

	var r0 []model.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Article, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Article); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentRepository_GetArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticles'
type ContentRepository_GetArticles_Call struct {
	*mock.Call
}

// GetArticles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ContentRepository_Expecter) GetArticles(ctx interface{}) *ContentRepository_GetArticles_Call {
	return &ContentRepository_GetArticles_Call{Call: _e.mock.On("GetArticles", ctx)}
}

func (_c *ContentRepository_GetArticles_Call) Run(run func(ctx context.Context)) *ContentRepository_GetArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ContentRepository_GetArticles_Call) Return(_a0 []model.Article, _a1 error) *ContentRepository_GetArticles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContentRepository_GetArticles_Call) RunAndReturn(run func(context.Context) ([]model.Article, error)) *ContentRepository_GetArticles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArticle provides a mock function with given fields: content
func (_m *ContentRepository) UpdateArticle(content *model.Article) error {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Article) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContentRepository_UpdateArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArticle'
type ContentRepository_UpdateArticle_Call struct {
	*mock.Call
}

// UpdateArticle is a helper method to define mock.On call
//   - content *model.Article
func (_e *ContentRepository_Expecter) UpdateArticle(content interface{}) *ContentRepository_UpdateArticle_Call {
	return &ContentRepository_UpdateArticle_Call{Call: _e.mock.On("UpdateArticle", content)}
}

func (_c *ContentRepository_UpdateArticle_Call) Run(run func(content *model.Article)) *ContentRepository_UpdateArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Article))
	})
	return _c
}

func (_c *ContentRepository_UpdateArticle_Call) Return(_a0 error) *ContentRepository_UpdateArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContentRepository_UpdateArticle_Call) RunAndReturn(run func(*model.Article) error) *ContentRepository_UpdateArticle_Call {
	_c.Call.Return(run)
	return _c
}

// NewContentRepository creates a new instance of ContentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContentRepository {
	mock := &ContentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
