with-expecter: true
dir: "mocks"
filename: "{{.InterfaceName}}.go"
outpkg: "mocks"
packages:
  cms/internal/repository:
    interfaces:
      Repository:
  cms/internal/usecase:
    interfaces:
      UseCase:
all: true
keeptree: true 
