with-expecter: True
issue-845-fix: True
disable-version-string: True
resolve-type-alias: False

dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{.InterfaceName | camelcase }}"
outpkg: "mocks"
filename: "{{.InterfaceName }}.go"

packages:
  admin_api_server/internal/controller:
    interfaces:
      getContents:
  admin_api_server/internal/usecase:
    interfaces:
      getContents:
