with-expecter: True
issue-845-fix: True
disable-version-string: True
resolve-type-alias: False

dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{.InterfaceName | camelcase }}"
outpkg: "mocks"
filename: "{{.InterfaceName }}.go"

packages:
  cms_api/internal/controller:
    interfaces:
      getContents:
  cms_api/internal/usecase/content:
    interfaces:
      getContents:
  cms_api/internal/infrastructure/repository:
    interfaces:
      ContentRepository:
