name: Go Test & Lint CI

on:
  push:
    branches-ignore:
      - main
    # paths:
    #   - 'cms_api/go/**'
jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cms_api/go
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: cms_api/go
          args: --timeout=5m 
