name: Go Test & Lint CI

on:
  push:
    branches-ignore:
      - main
    # paths:
    #   - 'cms_api/go/**'

env:
  WORKING_DIRECTORY: cms_api/go

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        run: make test

      - name: Run lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: ${{ env.WORKING_DIRECTORY }}
